export const UI_TEXTS = {
  title: '¿Qué hacemos hoy, Catita?',
  subtitle: 'Gira la ruleta y deja que la montaña decida 🌄',
  spinButton: 'Girar la ruleta',
  resultTitle: '¡Nuestro próximo panorama será...!',
  resultPrompt: '¿Te gusta este panorama o prefieres volver a girar?',
  acceptButton: 'Me encanta 💯',
  spinAgainButton: 'Volver a girar 🔄',
  acceptedTitle: '¡Quedó agendada nuestra salida! muak. ',
  acceptedMessage: 'Me encanta tu elección. Nos vemos pronto. Con cariño pa la número 1, reina máxima q me encanta🌄 ',
  closeButton: 'Cerrar',
  loading: 'Preparando nuestros panoramas...',
  loadError: 'No pude cargar la ruleta. Intentemos nuevamente.',
  notEnoughPlans: 'Necesitamos al menos dos panoramas para girar la ruleta.',
  spinError: 'La montaña se distrajo un poquito. Probemos otra vez.',
  retryButton: 'Reintentar',
  wheelDescription:
    'Ruleta con panoramas de cita. Gira para elegir nuestra próxima aventura.',
  musicPlay: 'Reproducir música',
  musicPause: 'Pausar música',
} as const;
